Repository api-ghost/api-ghost, pull requests merged in 2025-05, with the labels that each got.

#3 feat(core): Create scenario result domain model
  core/src/main/java/com/apighost/model/scenario/HTTPMethod.java
  core/src/main/java/com/apighost/model/scenario/ProtocolType.java
  core/src/main/java/com/apighost/model/scenario/result/ResponseBranch.java
  core/src/main/java/com/apighost/model/scenario/result/ScenarioResult.java
  core/src/main/java/com/apighost/model/scenario/result/StepResult.java
  core/src/main/java/com/apighost/model/scenario/result/ThenAction.java
  core/src/main/java/com/apighost/model/scenario/result/WhenCondition.java
Labels: BETA-0.0.1, feature

#5 feat(parser): scenario parser model to json
  parser/build.gradle
  parser/src/main/java/com/apighost/parser/scenario/writer/JsonScenarioResultWriter.java
  parser/src/main/java/com/apighost/parser/scenario/writer/ScenarioResultWriter.java
  parser/src/test/java/parser/scenario/writer/JsonScenarioResultWriterTest.java
Labels: BETA-0.0.1, feature

#6 feat(core): Create scenario YAML model
  core/src/main/java/com/apighost/model/scenario/test/Expected.java
  core/src/main/java/com/apighost/model/scenario/test/FormData.java
  core/src/main/java/com/apighost/model/scenario/test/Position.java
  core/src/main/java/com/apighost/model/scenario/test/Request.java
  core/src/main/java/com/apighost/model/scenario/test/RequestBody.java
  core/src/main/java/com/apighost/model/scenario/test/Route.java
  core/src/main/java/com/apighost/model/scenario/test/Scenario.java
  core/src/main/java/com/apighost/model/scenario/test/Step.java
  core/src/main/java/com/apighost/model/scenario/test/Then.java
Labels: BETA-0.0.1, feature

#7 feat(parser): scenario parser json to model
  core/build.gradle
  core/src/main/java/com/apighost/model/scenario/result/ResponseBranch.java
  core/src/main/java/com/apighost/model/scenario/result/ScenarioResult.java
  core/src/main/java/com/apighost/model/scenario/result/StepResult.java
  core/src/main/java/com/apighost/model/scenario/result/ThenAction.java
  core/src/main/java/com/apighost/model/scenario/result/WhenCondition.java
  parser/src/main/java/com/apighost/parser/scenario/reader/JsonScenarioResultReader.java
  parser/src/main/java/com/apighost/parser/scenario/reader/ScenarioResultReader.java
  parser/src/test/java/parser/scenario/writer/JsonScenarioResultReaderTest.java
Labels: BETA-0.0.1, feature

#12 chore: Change JsonScenarioResultReaderTest package path
  parser/src/test/java/parser/scenario/reader/JsonScenarioResultReaderTest.java
Labels: BETA-0.0.1, chore

#11 feat(core): Create scenario YAML reader, writer parser
  build.gradle
  core/build.gradle
  model/src/main/java/com/apighost/model/scenario/Scenario.java
  parser/build.gradle
  parser/src/main/java/com/apighost/parser/scenario/reader/ScenarioReader.java
  parser/src/main/java/com/apighost/parser/scenario/reader/YamlScenarioReader.java
  parser/src/main/java/com/apighost/parser/scenario/writer/ScenarioWriter.java
  parser/src/main/java/com/apighost/parser/scenario/writer/YamlScenarioWriter.java
  parser/src/test/java/parser/scenario/reader/YamlScenarioReaderTest.java
  parser/src/test/java/parser/scenario/writer/YamlScenarioWriterTest.java
Labels: BETA-0.0.1, feature

#15 chore: change scenario result model
  model/src/main/java/com/apighost/model/scenario/result/ResultStep.java
  parser/src/test/java/parser/scenario/reader/JsonScenarioResultReaderTest.java
  parser/src/test/java/parser/scenario/writer/JsonScenarioResultWriterTest.java
Labels: BETA-0.0.1, chore

#17 feat: create cli commands
  cli/build.gradle
  cli/src/main/java/com/apighost/cli/ApiGhostCli.java
  cli/src/main/java/com/apighost/cli/command/ViewResultListCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewScenarioCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewScenarioListCommand.java
  cli/src/main/java/com/apighost/cli/server/.gitkeep
  cli/src/main/java/com/apighost/cli/service/.gitkeep
  cli/src/main/java/com/apighost/cli/util/.gitkeep
  cli/src/main/java/com/apighost/cli/util/FileUtil.java
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  settings.gradle
Labels: BETA-0.0.1, feature

#16 feat: Create ScenarioValidator
  core/build.gradle
  core/src/main/java/com/apighost/scenario/validator/ScenarioValidator.java
Labels: BETA-0.0.1, feature

#19 feat(parser): Create TemplateConvertor
  core/build.gradle
  core/src/main/java/com/apighost/validator/ScenarioValidator.java
  core/src/test/java/core/validator/ScenarioValidatorTest.java
  parser/src/main/java/com/apighost/parser/template/TemplateConvertor.java
Labels: BETA-0.0.1, feature

#20 feat(CLI): Create commands and add logics
  cli/build.gradle
  cli/src/main/java/com/apighost/cli/ApiGhostCli.java
  cli/src/main/java/com/apighost/cli/command/FileType.java
  cli/src/main/java/com/apighost/cli/command/ShowGuiCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewResultCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewResultListCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewScenarioCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewScenarioListCommand.java
  cli/src/main/java/com/apighost/cli/config/.gitkeep
  cli/src/main/java/com/apighost/cli/server/.gitkeep
  cli/src/main/java/com/apighost/cli/server/JettyServer.java
  cli/src/main/java/com/apighost/cli/util/.gitkeep
  cli/src/main/java/com/apighost/cli/util/ConsoleOutput.java
  cli/src/main/java/com/apighost/cli/util/FileUtil.java
  cli/src/main/resources/index.html
  parser/src/main/java/com/apighost/parser/scenario/reader/YamlScenarioReader.java
Labels: BETA-0.0.1, feature

#22 feat(core): scenario test executor
  core/src/main/java/com/apighost/scenario/callback/ScenarioResultCallback.java
  core/src/main/java/com/apighost/scenario/executor/HTTPStepExecutor.java
  core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java
  core/src/main/java/com/apighost/scenario/executor/StepExecutor.java
  core/src/test/java/core/scenario/HTTPStepExecutorTest.java
  core/src/test/java/core/scenario/ScenarioTestExecutorTest.java
Labels: BETA-0.0.1, feature

#25 feat(web): servlet connect with gui
  cli/build.gradle
  cli/src/main/java/com/apighost/cli/command/FileType.java
  cli/src/main/java/com/apighost/cli/command/ViewResultCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewResultListCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewScenarioCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewScenarioListCommand.java
  cli/src/main/java/com/apighost/cli/server/JettyServer.java
  cli/src/main/java/com/apighost/cli/util/FileUtil.java
  settings.gradle
  web/build.gradle
  web/src/main/java/com/apighost/web/controller/ApiController.java
  web/src/main/java/com/apighost/web/controller/EndpointJsonController.java
  web/src/main/java/com/apighost/web/controller/ResultInfoController.java
  web/src/main/java/com/apighost/web/controller/ResultListController.java
  web/src/main/java/com/apighost/web/controller/ScenarioInfoController.java
  web/src/main/java/com/apighost/web/controller/ScenarioListController.java
  web/src/main/java/com/apighost/web/controller/ScenarioTestController.java
  web/src/main/java/com/apighost/web/filter/CorsFilter.java
  web/src/main/java/com/apighost/web/sevlet/ApiFrontControllerServlet.java
  web/src/main/java/com/apighost/web/util/FileType.java
  web/src/main/java/com/apighost/web/util/FileUtil.java
  web/src/main/java/com/apighost/web/util/JsonUtils.java
Labels: BETA-0.0.1, feature

#26 hotfix: Fix wrong getter
  model/src/main/java/com/apighost/model/scenario/result/ResultStep.java
Labels: BETA-0.0.1, hotfix

#28 hotfix: Apply changed isRequestSuccess getter
  core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java
  core/src/test/java/core/scenario/HTTPStepExecutorTest.java
  core/src/test/java/core/scenario/ScenarioTestExecutorTest.java
Labels: BETA-0.0.1, hotfix

#31 feat: structure of Endpoint
  model/src/main/java/com/apighost/model/collector/Endpoint.java
  model/src/main/java/com/apighost/model/collector/FieldMeta.java
  model/src/main/java/com/apighost/model/collector/Parameter.java
Labels: BETA-0.0.1, feature

#32 reafactor(util): Create util module
  settings.gradle
  util/build.gradle
  util/src/main/java/com/apighost/util/file/FileType.java
  util/src/main/java/com/apighost/util/file/FileUtil.java
  web/build.gradle
Labels: BETA-0.0.1, refactor

#34 feat: Create web endpoint collector
  model/src/main/java/com/apighost/model/config/ToolConfig.java
  web/build.gradle
  web/src/main/java/com/apighost/web/collector/ApiCollector.java
  web/src/main/java/com/apighost/web/controller/EndpointController.java
  web/src/main/java/com/apighost/web/controller/EndpointJsonController.java
  web/src/main/java/com/apighost/web/servlet/ApiFrontControllerServlet.java
  web/src/main/java/com/apighost/web/util/BasePathHolder.java
Labels: BETA-0.0.1, feature

#35 feat(generator): Implement Generator
  generator/build.gradle
  generator/src/main/java/com/apighost/generate/StructuredDataGenerator.java
  generator/src/main/java/com/apighost/loader/PropertyLoader.java
  generator/src/main/java/com/apighost/model/GeneratedData.java
  generator/src/main/java/com/apighost/model/ObjectMapperHolder.java
  generator/src/main/java/com/apighost/openai/FieldMetaPromptBuilder.java
  generator/src/main/java/com/apighost/openai/OpenAiStructuredDataGenerator.java
  generator/src/main/java/com/apighost/orchestrator/DataGenerationOrchestrator.java
  generator/src/main/java/com/apighost/orchestrator/OpenAiGenerateOrchestrator.java
  generator/src/main/java/com/apighost/parser/OpenAiResponseParser.java
  model/src/main/java/com/apighost/model/collector/FieldMeta.java
  settings.gradle
Labels: BETA-0.0.1, feature

#38 fix(web) : gui connect fix
  cli/src/main/java/com/apighost/cli/command/ShowGuiCommand.java
  cli/src/main/java/com/apighost/cli/server/JettyServer.java
  parser/src/main/java/com/apighost/parser/scenario/reader/YamlScenarioReader.java
  web/src/main/java/com/apighost/web/controller/ResultInfoController.java
  web/src/main/java/com/apighost/web/controller/ResultListController.java
  web/src/main/java/com/apighost/web/controller/ScenarioInfoController.java
Labels: BETA-0.0.1, fix

#40 feat(model): model for load test
  model/src/main/java/com/apighost/model/loadtest/parameter/LoadTest.java
  model/src/main/java/com/apighost/model/loadtest/parameter/LoadTestParameter.java
  model/src/main/java/com/apighost/model/loadtest/parameter/Stage.java
  model/src/main/java/com/apighost/model/loadtest/result/Endpoint.java
  model/src/main/java/com/apighost/model/loadtest/result/LoadTestSnapshot.java
  model/src/main/java/com/apighost/model/loadtest/result/LoadTestSummary.java
  model/src/main/java/com/apighost/model/loadtest/result/Result.java
  model/src/main/java/com/apighost/model/loadtest/result/metric/HttpReqDuration.java
  model/src/main/java/com/apighost/model/loadtest/result/metric/HttpReqFailed.java
  model/src/main/java/com/apighost/model/loadtest/result/metric/HttpReqs.java
  model/src/main/java/com/apighost/model/loadtest/result/metric/Iterations.java
  model/src/main/java/com/apighost/model/loadtest/result/metric/Vus.java
Labels: BETA-0.0.1, feature

#43 Feature/parser loadtest
  model/src/main/java/com/apighost/model/loadtest/parameter/Stage.java
  parser/src/main/java/com/apighost/parser/loadtest/reader/LoadTestParameterReader.java
  parser/src/main/java/com/apighost/parser/loadtest/reader/YamlLoadTestParameterReader.java
  parser/src/main/java/com/apighost/parser/loadtest/writer/LoadTestParameterWriter.java
  parser/src/main/java/com/apighost/parser/loadtest/writer/YamlLoadTestParameterWriter.java
  parser/src/test/java/loadtest/reader/YamlLoadTestParameterReaderTest.java
  parser/src/test/java/loadtest/writer/YamlLoadTestParameterWriterTest.java
  parser/src/test/java/parser/scenario/reader/JsonScenarioResultReaderTest.java
Labels: BETA-0.0.1, feature

#49 hotfix(model): import code of endpoint fixed
  model/src/main/java/com/apighost/model/loadtest/result/LoadTestSummary.java
Labels: bug, BETA-0.0.1

#46 Feat(core): Implementation of a HttpExecutor that covers FormData
  core/build.gradle
  core/src/main/java/com/apighost/scenario/builder/MultipartBodyPublisher.java
  core/src/main/java/com/apighost/scenario/executor/HTTPStepExecutor.java
  core/src/main/java/com/apighost/scenario/util/BasePathHolder.java
  core/src/test/java/core/scenario/HTTPStepExecutorTest.java
  util/src/main/java/com/apighost/util/file/FileType.java
  util/src/main/java/com/apighost/util/file/FileUtil.java
Labels: BETA-0.0.1, feature

#48 feat: Create load test result publisher
  loadtest/build.gradle
  loadtest/src/main/java/com/apighost/loadtest/publisher/CompositeResultPublisher.java
  loadtest/src/main/java/com/apighost/loadtest/publisher/ResultPublisher.java
  settings.gradle
Labels: BETA-0.0.1, feature

#47 Feat(parser): create loadtest-executer-param model and converter
  model/src/main/java/com/apighost/model/loadtest/parameter/LoadTestExecuteParameter.java
  model/src/main/java/com/apighost/model/loadtest/parameter/Stage.java
  model/src/main/java/com/apighost/model/loadtest/result/Result.java
  parser/build.gradle
  parser/src/main/java/com/apighost/parser/loadtest/converter/LoadTestParameterConverter.java
  parser/src/test/java/loadtest/writer/YamlLoadTestParameterWriterTest.java
  util/src/main/java/com/apighost/util/file/BasePathHolder.java
Labels: BETA-0.0.1, feature

#61 feat(core, util): websocket scenario support
  core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java
  core/src/main/java/com/apighost/scenario/executor/WebSocketStepExecutor.java
  core/src/main/java/com/apighost/util/ExecutionTimer.java
  util/src/main/java/com/apighost/util/file/TimeUtils.java
Labels: BETA-0.0.1, feature

#62 hotfix(model): change-endpoint-model
  model/src/main/java/com/apighost/model/collector/Endpoint.java
Labels: BETA-0.0.1, hotfix

#51 feat(cli): loadtest command
  cli/build.gradle
  cli/src/main/java/com/apighost/cli/ApiGhostCli.java
  cli/src/main/java/com/apighost/cli/command/ViewLoadTestParamCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewLoadTestParamListCommand.java
  cli/src/main/java/com/apighost/cli/command/ViewScenarioListCommand.java
  cli/src/main/java/com/apighost/cli/util/CliUtil.java
  util/src/main/java/com/apighost/util/file/FileType.java
Labels: BETA-0.0.1, feature

#64 hotfix(core): Change scenario when routes is null or empty
  core/src/main/java/com/apighost/scenario/executor/HTTPStepExecutor.java
  core/src/main/java/com/apighost/validator/ScenarioValidator.java
Labels: BETA-0.0.1, hotfix

#56 feat(web): apply error handling filter
  cli/src/main/java/com/apighost/cli/server/JettyServer.java
  web/src/main/java/com/apighost/web/controller/ApiController.java
  web/src/main/java/com/apighost/web/controller/EndpointController.java
  web/src/main/java/com/apighost/web/controller/ResultInfoController.java
  web/src/main/java/com/apighost/web/controller/ResultListController.java
  web/src/main/java/com/apighost/web/controller/ScenarioInfoController.java
  web/src/main/java/com/apighost/web/controller/ScenarioListController.java
  web/src/main/java/com/apighost/web/controller/ScenarioTestController.java
  web/src/main/java/com/apighost/web/filter/ErrorHandlingFilter.java
  web/src/main/java/com/apighost/web/servlet/ApiFrontControllerServlet.java
  web/src/main/java/com/apighost/web/util/ErrorCode.java
  web/src/main/java/com/apighost/web/util/JsonUtils.java
Labels: BETA-0.0.1, feature

#65 feat(generator): changing the parameters of the LLM body generator
  generator/src/main/java/com/apighost/model/GeneratedData.java
  generator/src/main/java/com/apighost/openai/FieldMetaPromptBuilder.java
  generator/src/main/java/com/apighost/orchestrator/DataGenerationOrchestrator.java
  generator/src/main/java/com/apighost/orchestrator/OpenAiGenerateOrchestrator.java
  generator/src/main/java/com/apighost/parser/OpenAiResponseParser.java
Labels: BETA-0.0.1, feature

#60 feat(web): create loadtest servlet
  web/build.gradle
  web/src/main/java/com/apighost/web/controller/LoadTestExportController.java
  web/src/main/java/com/apighost/web/controller/LoadTestInfoController.java
  web/src/main/java/com/apighost/web/controller/LoadTestListController.java
  web/src/main/java/com/apighost/web/filter/CorsFilter.java
  web/src/main/java/com/apighost/web/servlet/ApiFrontControllerServlet.java
Labels: BETA-0.0.1, feature

#66 refactor(model): Change load test model
  model/src/main/java/com/apighost/model/loadtest/parameter/LoadTestExecuteParameter.java
  model/src/main/java/com/apighost/model/loadtest/parameter/LoadTestParameter.java
  parser/src/test/java/parser/loadtest/reader/YamlLoadTestParameterReaderTest.java
  parser/src/test/java/parser/loadtest/writer/YamlLoadTestParameterWriterTest.java
Labels: BETA-0.0.1, refactor

#72 feat(cli): create ANSI escape logic
  cli/build.gradle
  cli/src/main/java/com/apighost/cli/publisher/BufferedCliPublisher.java
  cli/src/main/java/com/apighost/cli/util/console/AnsiEscapeUtil.java
  cli/src/main/java/com/apighost/cli/util/console/DynamicDisplayManager.java
  cli/src/main/java/com/apighost/cli/util/console/LoadTestReporter.java
Labels: BETA-0.0.1, feature

#67 feat(cli): create file delete command
  cli/src/main/java/com/apighost/cli/ApiGhostCli.java
  cli/src/main/java/com/apighost/cli/command/DeleteLoadTestParameterCommand.java
Labels: BETA-0.0.1, feature

#68 feat(loadtest): Create load test parameter
  loadtest/src/main/java/com/apighost/loadtest/parameter/StageExecuteParameter.java
  loadtest/src/main/java/com/apighost/loadtest/parameter/StageExecuteParameterResolver.java
  loadtest/src/main/java/com/apighost/loadtest/validator/LoadTestValidator.java
Labels: BETA-0.0.1, feature

#69 feat(loadtest): Create load test metrics managing
  loadtest/src/main/java/com/apighost/loadtest/metrics/LoadTestSnapshotAggregator.java
  loadtest/src/main/java/com/apighost/loadtest/metrics/MetricCalculator.java
  loadtest/src/main/java/com/apighost/loadtest/metrics/ResultBuffer.java
  util/src/main/java/com/apighost/util/file/TimeUtils.java
Labels: BETA-0.0.1, feature

#70 feat(loadtest): Create load test scheduler
  loadtest/src/main/java/com/apighost/loadtest/lifecycle/VuLifecycleManager.java
  loadtest/src/main/java/com/apighost/loadtest/scheduler/ResultScheduler.java
Labels: BETA-0.0.1, feature

#71 feat(loadtest): create load test executor
  loadtest/build.gradle
  loadtest/src/main/java/com/apighost/loadtest/LoadTestOrchestrator.java
  loadtest/src/main/java/com/apighost/loadtest/executor/LoadTestExecutor.java
  loadtest/src/main/java/com/apighost/loadtest/executor/RampUpStageExecutor.java
  loadtest/src/main/java/com/apighost/loadtest/executor/StageExecutor.java
Labels: BETA-0.0.1, feature

#73 feat(generator): Improve prompt handling
  generator/src/main/java/com/apighost/openai/FieldMetaPromptBuilder.java
  generator/src/main/java/com/apighost/openai/OpenAiStructuredDataGenerator.java
  generator/src/main/resources/openai.properties
Labels: BETA-0.0.1, feature

#76 hotfix(loadtest): ResultBuffer null check
  loadtest/src/main/java/com/apighost/loadtest/metrics/ResultBuffer.java
Labels: BETA-0.0.1, hotfix

#75 Feature/loadtest execute controller
  cli/src/main/java/com/apighost/cli/ApiGhostCli.java
  cli/src/main/java/com/apighost/cli/command/ExecuteLoadTestCommand.java
  web/src/main/java/com/apighost/web/controller/LoadTestExecuteController.java
  web/src/main/java/com/apighost/web/sse/SSEPublisher.java
Labels: BETA-0.0.1, feature

#78 hotfix(core): Add scenario execution if callback is null
  core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java
Labels: BETA-0.0.1, hotfix

#79 fix(web): bugs about responses
  web/src/main/java/com/apighost/web/controller/ResultInfoController.java
  web/src/main/java/com/apighost/web/controller/ScenarioExportController.java
  web/src/main/java/com/apighost/web/controller/ScenarioInfoController.java
  web/src/main/java/com/apighost/web/controller/ScenarioTestController.java
  web/src/main/java/com/apighost/web/util/FileUtil.java
Labels: bug, BETA-0.0.1

#81 fix(cli): dynamic load test result output
  cli/src/main/java/com/apighost/cli/command/ExecuteScenairoCommand.java
  cli/src/main/java/com/apighost/cli/publisher/BufferedCliPublisher.java
  cli/src/main/java/com/apighost/cli/util/console/AnsiEscapeUtil.java
  cli/src/main/java/com/apighost/cli/util/console/DynamicDisplayManager.java
  cli/src/main/java/com/apighost/cli/util/console/LoadTestReporter.java
Labels: bug, BETA-0.0.1

#80 hotfix(web): Fix servlet resource access problem
  cli/src/main/java/com/apighost/cli/server/JettyServer.java
  cli/src/main/resources/static/index.html
  web/src/main/java/com/apighost/web/servlet/RootRedirectServlet.java
  web/src/main/java/com/apighost/web/servlet/StaticResourceServlet.java
Labels: BETA-0.0.1, hotfix

#83 feat(web): scenario delete login and LLM
  cli/src/main/resources/logback.xml
  web/build.gradle
  web/src/main/java/com/apighost/web/controller/FileRemoveController.java
  web/src/main/java/com/apighost/web/controller/GenerateDataController.java
  web/src/main/java/com/apighost/web/controller/ScenarioExportController.java
  web/src/main/java/com/apighost/web/servlet/ApiFrontControllerServlet.java
  web/src/main/java/com/apighost/web/util/JsonUtils.java
  web/src/main/java/com/apighost/web/util/OpenAIKeyHolder.java
Labels: BETA-0.0.1, feature

#82 fix(core): scenario test to mock web server
  core/build.gradle
  core/src/test/java/core/scenario/HTTPStepExecutorTest.java
  core/src/test/java/core/scenario/ScenarioTestExecutorTest.java
Labels: BETA-0.0.1, fix

#85 fix(cli): added redirect error logic
  web/src/main/java/com/apighost/web/servlet/StaticResourceServlet.java
Labels: bug, BETA-0.0.1

#86 docs(readme): Update README.md
  LICENSE
  README.md
Labels: documentation, BETA-0.0.1
